# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name : 'SensoStatWeb-CI'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webApp: 'SensoStatWeb.WebApplication\SensoStatWeb.WebApplication.csproj'
  webApi: 'SensoStatWeb.Api\SensoStatWeb.Api.csproj'

steps:
- task: DotNetCoreInstaller@0
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory) -r win-x64 --self-contained true'
    zipAfterPublish: false
    workingDirectory: $(webApp)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'webApp'
    publishLocation: 'FilePath'
